language: ruby
notifications:
  disabled: true
only:
  - master
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby
  - rbx
script: bundle exec rake spec
before_script:
  - mysql -e 'create database association_observers;'
