language: ruby
notifications:
  disabled: true
only:
  - master
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
script: bundle exec rspec spec
before_script:
  - mysql -e 'create database association_observers;'
